"""Regenerate the release grids from data/releases.json.

Run after editing the JSON:    python3 tools/build.py

Only the block between the RELEASES:START / RELEASES:END markers in each page
is rewritten. Everything else — hero, intro copy, nav, footer — is hand-written
and left untouched.
"""
import json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
START = "  <!-- RELEASES:START — generated by tools/build.py, do not edit by hand -->"
END = "  <!-- RELEASES:END -->"

FLIP_SVG = ('<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" '
            'stroke-width="2.4" stroke-linecap="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8M21 '
            '12a9 9 0 0 1-15 6.7L3 16"/><path d="M21 3v5h-5M3 21v-5h5"/></svg>')

PLAY_SVG = '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M8 5v14l11-7z"/></svg>'

# An album tracklist is numbered — "01. Her", "05 — Sleaze", "3. Can We Try Again".
# A single lists versions of one song, never numbered. That is the only tell the
# source site gives us, so it is what decides LP vs Single. A bare digit followed
# by a space is not enough ("8 Days A Week (Sax Mix)" is a single), so a lone
# number needs its separator, or a two-digit index its leading zero.
# Mirrored in releaseFormat() in script.js, for the card the 404 page builds.
NUMBERED = re.compile(r'^\s*(?:\d{1,2}\s*[–—.)]|\d{2}\s)')


def esc(s):
    """& first, then the inch mark. Matches the entities already in the pages."""
    return s.replace("&", "&amp;").replace("″", "&Prime;")


def fmt(r):
    """LP or Single. "format" in the JSON wins where the tracklist can't tell."""
    if r.get("format"):
        return r["format"]
    return "LP" if any(NUMBERED.match(t) for t in r["tracks"]) else "Single"


def video_btn_html(r):
    """A release can carry one or more YouTube clips. data-videos is a JSON
    array of {id, label} read by the delegated handler in script.js — one
    button either plays straight or, with more than one clip, opens a small
    chooser. HTML-attribute-escaped (not esc(), which is for text nodes)
    since label text can carry an apostrophe into a single-quoted attribute."""
    videos = r.get("videos")
    if not videos:
        return ""
    attr = json.dumps(videos, ensure_ascii=False).replace("&", "&amp;").replace("'", "&#39;")
    return (f'\n          <button type="button" class="video-btn" data-videos=\'{attr}\' aria-label="Watch video">\n'
            f'            {PLAY_SVG}\n'
            f'          </button>')


def card_html(r):
    artist, title = esc(r["artist"]), esc(r["title"])
    missing = set(r.get("missing", []))
    lis = "\n".join(
        f'            <li class="missing">{esc(t)}</li>' if t in missing
        else f'            <li>{esc(t)}</li>'
        for t in r["tracks"]
    )
    legend = ('\n            <span class="legend"><span></span>missing from collection</span>'
              if missing else "")
    note = (f'\n          <p class="note">{esc(r["note"])}</p>' if r.get("note") else "")
    video_btn = video_btn_html(r)
    return f'''    <div class="card">
      <div class="card-inner" role="button" tabindex="0" aria-pressed="false" style="--cover-img:url('imgs/{r["image"]}')">
        <div class="face front">
          <img src="imgs/{r["image"]}" alt="{artist} – {title} sleeve" loading="lazy">
          <span class="format">{fmt(r)}</span>
          <span class="flip-hint" aria-hidden="true">
            {FLIP_SVG}
          </span>
          <div class="scrim">
            <p class="artist">{artist}</p>
            <p class="title">{title}</p>
          </div>
        </div>
        <div class="face back">
          <div class="back-head">
            <div class="back-head-text">
              <p class="artist">{artist} — {title}</p>
              <p class="label-name">{esc(r["label"])}</p>
            </div>{video_btn}
          </div>
          <ul class="tracks">
{lis}
          </ul>{note}
          <div class="back-foot">{legend}
            <button type="button">Flip back</button>
          </div>
        </div>
      </div>
    </div>
'''


def grids_html(releases):
    """Year headings, each followed by its grid. Years keep first-seen order."""
    years = list(dict.fromkeys(r["year"] for r in releases))
    out = []
    for y in years:
        cards = "\n".join(card_html(r) for r in releases if r["year"] == y)
        out.append(f'  <div class="year-rule" id="y{y}">{y}</div>\n'
                   f'  <div class="grid">\n\n{cards}\n  </div>\n')
    return "\n".join(out)


def jump_html(releases):
    years = list(dict.fromkeys(r["year"] for r in releases))
    if len(years) < 2:
        return None  # a one-button jump row is pointless
    links = "".join(f'      <a href="#y{y}">{y}</a>\n' for y in years)
    return ('    <nav class="year-jump" aria-label="Jump to year">\n'
            '      <span class="year-jump-label">Jump to</span>\n'
            f'{links}    </nav>')


def splice(page, body):
    path = ROOT / f"{page}.html"
    src = path.read_text(encoding="utf-8")
    if START not in src or END not in src:
        sys.exit(f"error: {page}.html is missing the RELEASES markers")
    head, rest = src.split(START, 1)
    _, tail = rest.split(END, 1)
    new = f"{head}{START}\n{body}{END}{tail}"
    changed = new != src
    path.write_text(new, encoding="utf-8")
    return changed


def main():
    data = json.loads((ROOT / "data" / "releases.json").read_text(encoding="utf-8"))
    for page, releases in data.items():
        changed = splice(page, grids_html(releases))
        n_missing = sum(len(r.get("missing", [])) for r in releases)
        n_lp = sum(1 for r in releases if fmt(r) == "LP")
        n_ep = sum(1 for r in releases if fmt(r) == "EP")
        n_single = len(releases) - n_lp - n_ep
        other = f", {n_ep} EP" if n_ep else ""
        print(f"  {page}.html: {len(releases)} releases "
              f"({n_lp} LP, {n_single} single{other}), "
              f"{sum(len(r['tracks']) for r in releases)} tracks, {n_missing} flagged"
              f"{'  (updated)' if changed else '  (no change)'}")
        jump = jump_html(releases)
        if jump and jump not in (ROOT / f"{page}.html").read_text(encoding="utf-8"):
            print(f"    note: the year-jump nav in {page}.html is out of date — "
                  f"years changed. Update it by hand or ask Claude.")


if __name__ == "__main__":
    main()
