"""Assemble dist/ — the exact folder that goes on the FTP host.

Run before uploading:    python3 tools/deploy.py

The repo stays flat and authorable: 1980s.html at the root, relative paths,
build.py untouched. What gets *published* is a different shape, and this script
is the only thing that knows about it:

  1980s.html   ->  1980s/index.html     so the live URL stays /1980s/
  relative     ->  root-relative        so 404.html works at any URL
  .htaccess    ->  written fresh        ErrorDocument, index, no listings

Nothing here edits the source. dist/ is disposable — delete and re-run freely.

Why root-relative: Apache serves 404.html *at the URL that missed*, so a page
at /some/deep/miss/ resolving "style.css" would ask for /some/deep/style.css
and get nothing. Only absolute paths survive that.
"""
import re, shutil, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DIST = ROOT / "dist"

# Flat source page -> where it lands in dist/. index.html and 404.html stay put:
# the first is the root document, the second is named by ErrorDocument.
PAGES = {
    "index.html":   "index.html",
    "1980s.html":   "1980s/index.html",
    "1990s.html":   "1990s/index.html",
    "contact.html": "contact/index.html",
    "404.html":     "404.html",
}

# How a link to each page is rewritten. 404.html is absent on purpose — it stays
# a file, not a directory, so the generic "/" + value rule handles it.
LINKS = {
    "index.html":   "/",
    "1980s.html":   "/1980s/",
    "1990s.html":   "/1990s/",
    "contact.html": "/contact/",
}

# Authoring and version-control clutter. Everything else in the repo ships.
EXCLUDE = {".git", ".gitignore", ".DS_Store", "CLAUDE.md", "tools", "dist", ".claude"}

# Left alone: anything already absolute, an anchor, or a non-http scheme.
KEEP = ("http://", "https://", "//", "#", "mailto:", "tel:", "data:", "/")
ATTR = re.compile(r'\b(href|src|poster|action)="([^"]+)"')

# script.js builds paths at runtime, out of reach of the attribute rewrite.
# Each pair must match exactly once — a silent miss ships a broken 404 page.
JS_EDITS = [
    ("fetch('data/releases.json')",
     "fetch('/data/releases.json')"),
    ('<img src="imgs/yep-avatar.jpg"',
     '<img src="/imgs/yep-avatar.jpg"'),
    ('\'<img src="imgs/\' + r.image',
     '\'<img src="/imgs/\' + r.image'),
    ("a.href = hit[0].page + '.html#y' + year",
     "a.href = '/' + hit[0].page + '/#y' + year"),
]

HTACCESS = """# Teddy Riley Productions — static archive site.
# Generated by tools/deploy.py. Edit the template there, not this file.

# 404.html is a real page with its own script, not Apache's default notice.
ErrorDocument 404 /404.html

# /1980s/ is served from 1980s/index.html.
DirectoryIndex index.html

# Never expose a bare file listing if an index is ever missing.
Options -Indexes

# The covers and fonts never change once published; the markup can change any
# day, and neither style.css nor script.js is fingerprinted — so cache the
# heavy static media only, and leave HTML/CSS/JS to revalidate as normal.
<IfModule mod_expires.c>
  ExpiresActive On
  ExpiresByType image/jpeg "access plus 1 month"
  ExpiresByType image/png  "access plus 1 month"
  ExpiresByType image/svg+xml "access plus 1 month"
  ExpiresByType video/mp4  "access plus 1 month"
  ExpiresByType font/woff2 "access plus 1 year"
</IfModule>
"""


def resolve(value):
    """One attribute value, rewritten for a site served from the domain root."""
    if value.startswith(KEEP):
        return value
    page, sep, frag = value.partition("#")
    if page in LINKS:
        return LINKS[page] + (sep + frag if sep else "")
    return "/" + value


def rewrite_html(text):
    return ATTR.sub(lambda m: f'{m.group(1)}="{resolve(m.group(2))}"', text)


def rewrite_js(text):
    for old, new in JS_EDITS:
        if text.count(old) != 1:
            sys.exit(f"error: script.js no longer contains exactly one\n"
                     f"  {old}\n"
                     f"Someone edited it. Update JS_EDITS in tools/deploy.py to match.")
        text = text.replace(old, new)
    return text


def copy_tree():
    """Mirror the repo into dist/, minus the authoring clutter."""
    def ignore(directory, names):
        skip = {n for n in names if n in EXCLUDE or n == ".DS_Store"}
        # The flat pages are placed by hand afterwards, rewritten.
        if Path(directory) == ROOT:
            skip |= set(PAGES)
        return skip

    if DIST.exists():
        shutil.rmtree(DIST)
    shutil.copytree(ROOT, DIST, ignore=ignore)


def main():
    copy_tree()

    for source, target in PAGES.items():
        src = ROOT / source
        if not src.exists():
            sys.exit(f"error: {source} is missing from the repo")
        out = DIST / target
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(rewrite_html(src.read_text(encoding="utf-8")), encoding="utf-8")
        print(f"  {source:<13} -> {target}")

    js = DIST / "script.js"
    js.write_text(rewrite_js(js.read_text(encoding="utf-8")), encoding="utf-8")
    print("  script.js       -> runtime paths made root-relative")

    (DIST / ".htaccess").write_text(HTACCESS, encoding="utf-8")
    print("  .htaccess       -> written")

    files = [p for p in DIST.rglob("*") if p.is_file()]
    size = sum(p.stat().st_size for p in files)
    print(f"\n  dist/: {len(files)} files, {size / 1e6:.0f} MB — upload the contents to the web root")


if __name__ == "__main__":
    main()
